defaults:
  - pruning: ocap  
  - model: vgg16
  - dataset: cifar10
  - _self_

selected_classes: [0,1,2,3]
num_pruning_samples: 512
replace_last_layer: true
log_results: false
run_name: null

training:
  train: false
  batch_size_train: 256
  batch_size_test: 256
  lr: 0.001
  weight_decay: 1e-5
  epochs: 50
  optimizer: adamw



