defaults:
  - pruning: ocap  
  - model: vgg16
  - dataset: cifar10
  - _self_

selected_classes: [0,1,2] 
num_pruning_samples: 512
replace_last_layer: true
log_results: true
run_name: null
device: null
resnet_zero_insertion: false
inference_with_onnx: false

training:
  train: false
  use_data_augmentation: false # set to false to make results deterministic in pruning
  retrain_after_pruning: true
  retrain_epochs: 10
  batch_size_train: 256
  batch_size_test: 256
  lr: 0.0005
  lr_retrain: 0.00001
  weight_decay: 1e-4
  epochs: 30
  optimizer: adamw
  use_pretrained_model: true
