defaults:
  - pruning: ocap
  - model: vgg16
  - dataset: imagenet
  - _self_

selected_classes: [10,20,30]
num_pruning_samples: null
replace_last_layer: true
log_results: true
run_name: ocap_test
device: null
resnet_zero_insertion: false
inference_with_onnx: false
use_knowledge_distillation: false

training:
  train: true
  use_data_augmentation: true # set to False to make results deterministic in pruning
  retrain_after_pruning: true
  retrain_epochs: 100
  batch_size_train: 128
  batch_size_test: 128
  lr: 0.0005
  lr_retrain: 0.00001
  weight_decay: 1e-4
  epochs: 30
  optimizer: adamw
  use_pretrained_model: true
