defaults:
  - pruning: ocap  
  - model: vgg16
  - dataset: cifar10
  - _self_

selected_classes: [0,1]
num_pruning_samples: 512

training:
  train: false
  batch_size_train: 256
  batch_size_test: 256
  lr: 0.001
  weight_decay: 0
  epochs: 20
  optimizer: adam



