name: lrp
pruning_ratio: 0.7

# [0.00,0.1 ,0.2 ,0.3 ,0.34,0.38,0.41,0.45,0.5 ,0.6 ,0.7 ,0.8 ,0.85,0.9 ,0.95,0.97] #vgg16 imagenet
# [0.00,0.1 ,0.15,0.2 ,0.35,0.45,0.55,0.65,0.70,0.75,0.8 ,0.85] #resnet18 imagenet
# [0,0.2,0.347,0.363,0.38,0.395,0.41,0.426,0.442, 0.7,0.8,0.85,0.9,0.95,0.97] cifar10 vgg16
# [0,0.2,0.165,0.225,0.295,0.37,0.46,0.55,0.65,0.70,0.75,0.77] # cifar10 resnet18