name: ocap
pruning_ratio: [0.00, 0.85, 0.88, 0.90, 0.91, 0.945, 0.96, 0.973, 0.98, 0.988, 0.9994] #vgg16 imagenet
activation_func: leaky_relu

# [0.00 ,0.85 ,0.88 ,0.90 ,0.91 ,0.945,0.96 ,0.973,0.98 ,0.988,0.9994] #vgg16 imagenet 
# [0.00 ,0.85 ,0.88 ,0.90 ,0.92 ,0.945,0.955,0.975,0.988,0.994,0.997] #resnet imagenet 
# [0.0, 0.25,0.36,0.48,0.61,0.72,0.85,0.96,0.991,0.995,0.997,0.999] # vgg16 cifar10 
# [0.00,0.915,0.95,0.97,0.982,0.99,0.995,0.999] # resnet18 cifar10