name: torchpruner
pruning_ratio: 0.7
attribution: taylor # taylor, apoz, sensitivity

# [0,0.1,0.2,0.3,0.315,0.332,0.348,0.364,0.38,0.4,0.7,0.8,0.85,0.9] #vgg16
# [0,0.1,0.17,0.26,0.35,0.47,0.60,0.73,0.81,0.88] #resnet18